### PR TITLE
Support several clients

### PR DESCRIPTION
**Pull request by vrutkovs**
Pass urls to WEBDRIVER_WHARF_CLIENTS env var and use a client with a minimal number of containers running as a client for current operation

### CODE REVIEW

**Comment by vrutkovs** [comment]
@psav - any suggestions?

**Comment by jchristi** [comment]
being able to work with remote docker engines is definitely a good enhancement :+1:

**Comment by RonnyPfannschmidt** [comment]
should use a swarm instead

**Comment by jchristi** [comment]
Will docker swarm work with the latest and/or future version of the webdriver-wharf?

**Comment by RonnyPfannschmidt** [comment]
@jchristi my understanding is that a docker swarm exposes the same api as a normal docker node,

if there is an difference i missed then please let me know so we can treat that as a bug and fix

**Comment by RonnyPfannschmidt** [comment]
closing this off as i just noticed that without a change to the database this one completely breaks integrity
as operations on specific containers have to pick a specific client

**Pull request closed without merging**
